/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-top': 'var(--bg-top)',
        'bg-mid': 'var(--bg-mid)',
        'bg-bot': 'var(--bg-bot)',
        'title-fill': 'var(--title-fill)',
        'title-outline': 'var(--title-outline)',
        'title-shadow': 'var(--title-shadow)',
        'stat': 'var(--stat)',
        'btn-face': 'var(--btn-face)',
        'btn-edge': 'var(--btn-edge)',
        'btn-text': 'var(--btn-text)',
        'pill-face': 'var(--pill-face)',
        'pill-outline': 'var(--pill-outline)',
        'pill-shade': 'var(--pill-shade)',
        'gear': 'var(--gear)',
        'gear-edge': 'var(--gear-edge)',
        'opt-face': 'var(--opt-face)',
        'opt-face-sel': 'var(--opt-face-sel)',
        'opt-shade-sel': 'var(--opt-shade-sel)',
        'opt-text-sel': 'var(--opt-text-sel)',
        'panel-bg': 'var(--panel-bg)',
        'panel-edge': 'var(--panel-edge)',
        'close-face': 'var(--close-face)',
        'close-mark': 'var(--close-mark)',
        'label-band': 'var(--label-band)',
        'label-text': 'var(--label-text)',
        'pix-frame': 'var(--pix-frame)',
        'arrow-next': 'var(--arrow-next)',
        'arrow-prev': 'var(--arrow-prev)',
        'board-bg': 'var(--board-bg)',
        'board-edge': 'var(--board-edge)',
        'grid': 'var(--grid)',
        'block': 'var(--block)',
        'block-hi': 'var(--block-hi)',
        'dim': 'var(--dim)',
        'dpad-bg': 'var(--dpad-bg)',
        'dpad-edge': 'var(--dpad-edge)',
        'dpad-arrow': 'var(--dpad-arrow)',
      },
      fontFamily: {
        'pixel': ['LomoWebPixelLTStd-5', 'Press Start 2P', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
};
